#!/bin/bash

# Exit immediately if a command exits with a non-zero status
set -e

# Get version from argument, default to 1.0.0 if not provided
VERSION=${1:-1.0.0}

echo "Starting build process for version $VERSION..."

# 1. Run npm run build
echo "Running npm run build..."
if ! npm run build; then
    echo "npm run build failed or was denied permission, falling back to direct webpack compilation..."
    node node_modules/webpack/bin/webpack.js
fi

# 2. Run npm run build:legacy
echo "Running npm run build:legacy..."
if ! npm run build:legacy; then
    echo "npm run build:legacy failed or was denied permission, falling back to direct webpack legacy compilation..."
    node node_modules/cross-env/dist/bin/cross-env.js BUILD_TARGET=legacy node node_modules/webpack/bin/webpack.js
fi

# 3. Rename license file
echo "Renaming license files..."
if [ -f "build/options-legacy.js.LICENSE.txt" ]; then
    mv build/options-legacy.js.LICENSE.txt build/options.js.LICENSE.txt
    echo "Renamed build/options-legacy.js.LICENSE.txt to build/options.js.LICENSE.txt"
else
    echo "Warning: build/options-legacy.js.LICENSE.txt not found. Skipping rename."
fi
if [ -f "build/settings-legacy.js.LICENSE.txt" ]; then
    mv build/settings-legacy.js.LICENSE.txt build/settings.js.LICENSE.txt
    echo "Renamed build/settings-legacy.js.LICENSE.txt to build/settings.js.LICENSE.txt"
else
    echo "Warning: build/settings-legacy.js.LICENSE.txt not found. Skipping rename."
fi

# 4. Add headers
HEADER="/*
 * OptionBay - Product Options and Addons
 * Copyright (c) $(date +%Y) WP Anchor Bay - https://wpanchorbay.com
 *
 * This software is licensed under the GPLv2 or later.
 * This file is generated from un-compiled source code. Do not edit this file directly.
 *
 * Source Code (Root): https://github.com/wpanchorbay/product-options-addons-woo/tree/$VERSION/
 *
 * For license information please see options.js.LICENSE.txt or settings.js.LICENSE.txt
 */"

# List of files to edit
FILES=("build/options.js" "build/options-legacy.js" "build/settings.js" "build/settings-legacy.js")

# Loop through each file and prepend the header
for file in "${FILES[@]}"; do
    if [ -f "$file" ]; then
        echo "Adding header to $file..."
        echo "$HEADER" | cat - "$file" > "${file}.tmp" && mv "${file}.tmp" "$file"
        echo "Successfully added header to $file"
    else
        echo "Warning: File $file not found."
    fi
done

echo "Build and header addition complete for version $VERSION."
